import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex m-2 p-2 gap-2">
        <div className="text-white">Home</div>
        <div className=" text-white">About</div>
      </div>
    </div>
  );
}
